[theme]

# Primary accent for interactive elements
primaryColor = '#007BFF'

# Background color for the main content area
backgroundColor = '#F5F5f7'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#F5F7F7'

# Color used for almost all text
textColor = '#1D1D1F'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "monospace"
font = "monospace"
